server:
  port: 8082

spring:
  jackson:
    deserialization:
      fail-on-invalid-subtype: true
      fail-on-unknown-properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/transactiondb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
##      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
##    properties:
##      schema.registry.url: http://localhost:8081
